def foo():
    x = 100/0
    
    
# try:
foo()
# except ValueError:
#     print('error')